# Generated by Django 3.0.3 on 2020-02-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situation_report_app', '0003_auto_20200226_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Information',
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
    ]
