# Generated by Django 3.0.3 on 2020-03-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situation_report_app', '0007_auto_20200310_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Article',
        ),
    ]
