# Generated by Django 3.0.3 on 2020-03-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation_report_app', '0011_remove_article_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
