# Generated by Django 3.0.3 on 2020-03-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation_report_app', '0014_auto_20200314_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(max_length=64),
        ),
    ]
