# Generated by Django 3.0.3 on 2020-03-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation_report_app', '0015_auto_20200315_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
