# Generated by Django 3.0.3 on 2020-03-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation_report_app', '0016_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
