# Generated by Django 3.0.3 on 2020-02-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation_report', '0002_auto_20200226_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.BooleanField(default=True),
        ),
    ]
