# Generated by Django 3.0.3 on 2020-02-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situation_report', '0004_auto_20200226_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='source',
            new_name='url',
        ),
    ]
