# Generated by Django 3.0.4 on 2020-03-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situation_report', '0006_auto_20200228_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='place_name',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='country',
            new_name='country_name',
        ),
        migrations.RemoveField(
            model_name='new',
            name='create',
        ),
        migrations.RemoveField(
            model_name='new',
            name='text',
        ),
        migrations.AddField(
            model_name='new',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='new_cases',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='new_deaths',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_cases',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_deaths',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_recovered',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
