# Generated by Django 3.0.3 on 2020-03-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situation_report', '0010_auto_20200313_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
    ]
